package utilities;

public enum RequestType {
    SIGNUP_REQUEST,
    LOGIN_REQUEST,
    LOGOUT_REQUEST,
    CREATE_CODEDOC_REQUEST,
    GET_ME_REQUEST,
    VERIFY_USER_REQUEST,
    FETCH_CODEDOC_REQUEST,
    ADD_ACCESSOR_TO_CODEDOC_REQUEST,
    UPDATE_CODEDOC_REQUEST,
    DELETE_CODEDOC_REQUEST
}
