package utilities;

public enum ResponseType {
    SIGNUP_RESPONSE,
    LOGIN_RESPONSE,
    LOGOUT_RESPONSE,
    CREATE_CODEDOC_RESPONSE,
    GET_ME_RESPONSE,
    FETCH_CODEDOC_RESPONSE,
    ADD_ACCESSOR_TO_CODEDOC_RESPONSE,
    COMPILE_CODEDOC_RESPONSE,
    RUN_CODEDOC_RESPONSE,
    UPDATE_CODEDOC_RESPONSE,
    DELETE_CODEDOC_RESPONSE
}