package utilities;

public enum RequestType {
    SIGNUP_REQUEST,
    LOGIN_REQUEST,
    LOGOUT_REQUEST,
    CREATE_CODEDOC_REQUEST,
    GET_ME_REQUEST,
    VERIFY_USER_REQUEST,
    FETCH_CODEDOC_REQUEST,
    ADD_ACCESSOR_TO_CODEDOC_REQUEST,
    UPDATE_CODEDOC_REQUEST,
    DELETE_CODEDOC_REQUEST,
    LOAD_EDITOR_REQUEST,
    INVITE_COLLABORATOR_REQUEST,
    ACCEPT_INVITE_REQUEST,
    REJECT_INVITE_REQUEST,
    FETCH_INVITE_REQUEST,
    RUN_CODEDOC_REQUEST,
    SAVE_CODEDOC_REQUEST
}
