package utilities;

/**
 * Different responses received from server
 */
public enum ResponseType {
    SIGNUP_RESPONSE,
    LOGIN_RESPONSE,
    LOGOUT_RESPONSE,
    CREATE_CODEDOC_RESPONSE,
    GET_ME_RESPONSE,
    FETCH_CODEDOC_RESPONSE,
    ADD_ACCESSOR_TO_CODEDOC_RESPONSE,
    RUN_CODEDOC_RESPONSE,
    COMPILE_CODEDOC_RESPONSE,
    UPDATE_CODEDOC_RESPONSE,
    DELETE_CODEDOC_RESPONSE,
    LOAD_EDITOR_RESPONSE,
    INVITE_COLLABORATOR_RESPONSE,
    FETCH_COLLABORATOR_RESPONSE,
    REMOVE_COLLABORATOR_RESPONSE,
    CHANGE_COLLABORATOR_RIGHTS_RESPONSE,
    ACCEPT_INVITE_RESPONSE,
    REJECT_INVITE_RESPONSE,
    FETCH_INVITE_RESPONSE,
    SAVE_CODEDOC_RESPONSE,
    EDITOR_CONNECTION_RESPONSE,
    EDITOR_CLOSE_RESPONSE
}